### ISSUE TITLE
Dataset Description

### ISSUE THREAD

**Issue by pribadihcr** [alisonhc/change-complexity#1]
Hi, can you give a detailed data description in the README?

for example in paranmt-cefr, there are many version of the dataset. Add description about the meaning of each named dataset should be helpful. Also, for the cefr level classification model, which dataset is used?.

**Comment by alisonhc** [comment]
Hi Pribadi, thanks for your interest in the data. 

1. I've added a table in the readme explaining the meaning of the naming choices used for each dataset; let me know if anything is unclear there.
2. Regarding the CEFR dataset, we mention in the paper that [this request form](https://languageresearch.cambridge.org/academic-research-request-form) can be used to obtain the data, which already [exists online](https://englishprofile.org/). We do not have permission to post it publicly.

**Comment by pribadihcr** [comment]
Thank you very much
